import { NextResponse } from 'next/server'
import { z } from 'zod'
import { auth } from '@clerk/nextjs/server'
import { prisma, Prisma } from '@repo/database'

/**
 * POST /api/v1/user/web-push
 *   Save a Web Push subscription for the authenticated user. The browser's
 *   PushManager.subscribe() returns a PushSubscription object — we accept
 *   its JSON serialization and persist it to user.webPushSubscription.
 *
 * DELETE /api/v1/user/web-push
 *   Clear the subscription (when the user opts out, or when the cron
 *   sees a 404/410 from the push service and tells the user to re-up).
 *
 * Shape validation matches the W3C Push API spec. The endpoint URL is
 * generated by the browser's push service (FCM for Chrome, Mozilla for
 * Firefox, WebPush.apple.com for Safari) and must be opaque to us.
 */

const subscriptionSchema = z.object({
  endpoint: z.string().url().max(2048),
  expirationTime: z.number().nullable().optional(),
  keys: z.object({
    p256dh: z.string().max(512),
    auth: z.string().max(256),
  }),
})

export async function POST(req: Request) {
  const { userId: clerkId } = await auth()
  if (!clerkId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  let body: unknown
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }
  const parsed = subscriptionSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: 'Invalid subscription shape' }, { status: 400 })
  }

  await prisma.user.update({
    where: { clerkId },
    data: { webPushSubscription: parsed.data },
  })

  return NextResponse.json({ ok: true })
}

export async function DELETE() {
  const { userId: clerkId } = await auth()
  if (!clerkId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  await prisma.user.update({
    where: { clerkId },
    // Prisma requires the JsonNull sentinel for nullable Json fields,
    // not `null` itself — explicit DB NULL vs JSON null distinction.
    data: { webPushSubscription: Prisma.JsonNull },
  })

  return NextResponse.json({ ok: true })
}
